### ISSUE TITLE
auto renderer not working correctly

### ISSUE THREAD

**Issue by Wastlbri** [RussDev7/CoreKeepersWorkshop#12]
hello, i just downloaded this to get a nice view of my map and it doesn't seem to work very well. im using version 1.3.5.9. the main issue is that the map doesnt seem to be getting revealed properly.
![image_2023-12-10_061945511](https://github.com/RussDev7/CoreKeepersWorkshop/assets/153440667/b4e5d2e9-9992-4418-b99a-b4feeb2a84ef)
this is an image of my map after about an hour of fiddling with different reveal range sizes, game settings, and whatnot. is this something there is a fix to? or am i just doing something wrong?
thanks.

**Comment by RussDev7** [comment]
Thank you for taking the time to write in. Since one of the recent updates in the game actually reworked the map rendering. They reduced the max rendering down to 12. While 12 is still larger then the default 7, the set reveal range feature still enables the dev map rendering too. I have kept values above 12 in hopes they rework it once again. In the next updates I will cap this value out at 12 to prevent this issue from re-occurring to unsuspecting people.

**Comment by Wastlbri** [comment]
thank you for letting me know. (:
