### ISSUE TITLE
Map rendering doesn't seem to be working.

### ISSUE THREAD

**Issue by Cerneto** [RussDev7/CoreKeepersWorkshop#9]
Whenever I try to get addresses for the map it always throws an exception out. I am wondering if it is somehow user error or if the program is actually bugged.
![image_2023-10-04_014804596](https://github.com/RussDev7/CoreKeepersWorkshop/assets/26750390/45e13fed-c1e0-4fde-a79a-dd1dd3f6c253)
This is everything in the details tab of the error:
https://pastebin.com/RQRGQWp4

**Comment by RussDev7** [comment]
Thank you for writing in this issue! The game just had a huge overhaul since they released support for their modding API.

I looked into this error and found it's being caused from the mod trying to search the memory of a module named `GameAssembly.dll` that no longer exists since their new update.

As a result this had also broke all the player tools as well. I will be looking for a fix to map stuff shortly. None the less I'm going to be pushing a patch to fix all the current player tools. 
![Capture](https://github.com/RussDev7/CoreKeepersWorkshop/assets/33048298/7452dad9-b9b4-43f1-8771-2c28157d5b41)

**Comment by Cerneto** [comment]
Oh, Neat. Thank you for all your hard work on creating and maintaining this program!

**Comment by RussDev7** [comment]
Good news! The Dev Map and Map Render Range addresses have been found once again and I will be updating the mod shortly. 
![RevealTesting](https://github.com/RussDev7/CoreKeepersWorkshop/assets/33048298/065ccd9b-9c39-40f1-a5b9-906653a2afbe)
